### ISSUE TITLE
3.67 doesn’t work 

### ISSUE THREAD

**Issue by Clvers** [OperationNT414C/ShellSecBat#4]

**Comment by OperationNT414C** [comment]
As I don't wish to update my devices over 3.65, I usaly rely on nowrep to find offsets (ShellBat plugin creator). But he already closed an issue and tell the user to update on 3.68.
I could try to find the offset but it requires decrypted "SceShell" from 3.67. If you wish to help me, you need to provide me this file. Here is an application which allow to dump decrypted FW parts:

[vitadump-master.zip](https://github.com/OperationNT414C/ShellSecBat/files/2181391/vitadump-master.zip)

Can you please install "mDump.vpk" and launch it with kernel rights ("allow unsafe homebrew")? After about 1 minute, it should create a "ux0:dump" directory which will contain files I need: "SceShell.elf" and "SceShell_info.bin".
As those file are proprietary code, you cannot put them on github. Can you send me those files to my email address "fakemail_255 at hotmail dot fr"?
Thank you very much for your help.

**Comment by victorafs** [comment]
I make the dump and send for you.

**Comment by OperationNT414C** [comment]
I received the file, thank you very much.
I will be busy next week so I take a look to dissassembled code in 10 days.
I will try to publish on this thread "testable" versions of the plugin. I will need help to validate those tests versions.

**Comment by OperationNT414C** [comment]
In fact, I just take a look at the code it didn't evolved between 3.65 and 3.68 (so I guess 3.67 is the same). The only think I need is the "SceShell" module NID for 3.67 and I could retreive it from "download_enabler" plugin.
So here is a version where I add this module NID to the offset test:

[ShellSecBat_3.67_RC1.zip](https://github.com/OperationNT414C/ShellSecBat/files/2186382/ShellSecBat_3.67_RC1.zip)

Can you tell me if it solves the issue?
Thank you for your help.

**Comment by victorafs** [comment]
its work for me on the 3.67, just made the download and replace the file, when restart and active h-encore, the plugin work

**Comment by OperationNT414C** [comment]
Thank you for the validation. I just published this version as V8 ;-)
