### ISSUE TITLE
Can't add a date

### ISSUE THREAD

**Issue by chronoss09** [OperationNT414C/ShellSecBat#5]
I test it on 3.65 and 3.68 with the same config file but can't show me the date, only hr and sec : 
Features:11
Time:100/
Drives:11.111111
LeftKey:101
RightKey:201

**Comment by OperationNT414C** [comment]
Your configuration "Time:100/" tells to not display date and not display year.
Replace it with "Time:111/".
Look at "readme.md" file for further information.
You can also get the config file in "ShellDateSecBat" folder from this repository.

**Comment by chronoss09** [comment]
Great, it work now !

Thanks a lot !
