### ISSUE TITLE
mount point max size mismatch

### ISSUE THREAD

**Issue by eviltpot** [OperationNT414C/ShellSecBat#7]
have a 2tb usb hdd on pstv mounted as ux0
vitashell shows 1.09tb/1.82tb usage
plugin in reporting 749gb free / 1tb total

**Comment by OperationNT414C** [comment]
Hello,
I don't have an HDD formated for PS TV with that size but when I simulate the code with big numbers, I think there is a potential issue in decimal computation part. Can you please tell me if attached version fixes the issue?
Thank you for your feedback.

[ShelSecBat_BigSizeFix.zip](https://github.com/OperationNT414C/ShellSecBat/files/3512201/ShelSecBat_BigSizeFix.zip)

**Comment by eviltpot** [comment]
yes thanks
ux0 now reporting 1.83tb total.   much closer than what it was reading before

**Comment by OperationNT414C** [comment]
Thank you for the validation, I just published a new version with this fix.
